export const MOCK_NEWS = {
    "pagination": {
        "limit": 25,
        "offset": 0,
        "count": 25,
        "total": 10000
    },
    "data": [
        {
            "author": "Larissa Holzki",
            "title": "Black Forest Labs : Zwei große US-Investoren wollen offenbar Freiburger KI-Firma finanzieren",
            "description": "Einem Bericht zufolge leiten Salesforce und AMP eine neue Finanzierungsrunde bei Black Forest Labs. Damit soll der Spezialist für KI-Bilder weiter mit Google mithalten können.",
            "url": "https://www.handelsblatt.com/technik/ki/black-forest-labs-zwei-grosse-us-investoren-wollen-offenbar-freiburger-ki-firma-finanzieren/100163069.html",
            "source": "Handelsblatt",
            "image": "https://images.handelsblatt.com/AywD1Nr3M35r/cover/900/506/0/0/0/833/0.5/0.5/robin-rombach-co-gruender-und-ceo-black-forest-labs-tech-2025.jpg",
            "category": "general",
            "language": "de",
            "country": "de",
            "published_at": "2025-10-14T02:52:44+00:00"
        },
        {
            "author": "Bloomberg News",
            "title": "India, EU Close To Resolving Clearing House Oversight Dispute",
            "description": "India, EU Close To Resolving Clearing House Oversight Dispute",
            "url": "https://www.ndtvprofit.com/business/india-eu-close-to-resolving-clearing-house-oversight-dispute",
            "source": "Bloomberg | Latest And Live Business",
            "image": null,
            "category": "business",
            "language": "en",
            "country": "us",
            "published_at": "2025-10-14T02:52:39+00:00"
        },
        {
            "author": "Famagusta Gazette",
            "title": "Cyprus Weather Forecast: Mild Conditions with Patchy Clouds",
            "description": "A weak low-pressure system is affecting the region, bringing mostly clear skies with occasional patches of increased cloud cover, according&#8230;",
            "url": "https://famagusta-gazette.com/cyprus-weather-forecast-mild-conditions-with-patchy-clouds/",
            "source": "famagusta-gazette",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2025-10-14T02:52:39+00:00"
        },
        {
            "author": "Tom Zaunmayr",
            "title": "OPINION: Pilbara water wars to reach boiling point",
            "description": "Water will be the single biggest reputational and economic risk facing industry and government in the Pilbara by 2030.",
            "url": "https://www.businessnews.com.au/article/OPINION-Pilbara-water-wars-to-reach-boiling-point",
            "source": "Business News.com.au",
            "image": "https://www.businessnews.com.au/sites/default/files/2025-10/Circular%20Pool%203%20TZ%20%281%29%20copy.jpg",
            "category": "business",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:52:31+00:00"
        },
        {
            "author": "redaktion@ad-hoc-news.de",
            "title": "Schaeffler Aktie: Spannung steigt!",
            "description": "Schaeffler Aktie: Spannung steigt!",
            "url": "https://www.ad-hoc-news.de/boerse/news/ueberblick/schaeffler-aktie-spannung-steigt/68268197",
            "source": "ad-hoc-news",
            "image": null,
            "category": "general",
            "language": "de",
            "country": "de",
            "published_at": "2025-10-14T02:52:25+00:00"
        },
        {
            "author": null,
            "title": "Altria: The Company Is Ready To Make A Move Into The Smokeless Segment",
            "description": "Altria: The Company Is Ready To Make A Move Into The Smokeless Segment",
            "url": "https://seekingalpha.com/article/4829662-altria-the-company-is-ready-to-make-a-move-into-the-smokeless-segment?source=feed_all_articles",
            "source": "Seeking Alpha",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2025-10-14T02:52:15+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.brisbanetimes.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "Brisbane Times",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.brisbanetimes.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_national",
            "source": "brisbanetimes",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.theage.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_national",
            "source": "The Age",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.smh.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.smh.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_national",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.watoday.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_national",
            "source": "watoday",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.theage.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "The Age",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.watoday.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "watoday",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "William Ton",
            "title": "Brittany Higgins faces bankruptcy action by former boss",
            "description": "Linda Reynolds successfully sued Higgins over a series of social media posts the ex-Liberal senator believed damaged her reputation.",
            "url": "https://www.watoday.com.au/national/western-australia/brittany-higgins-faces-bankruptcy-action-by-former-boss-20251014-p5n2g4.html?ref=rss&utm_medium=rss&utm_source=rss_national_western-australia",
            "source": "watoday",
            "image": "https://static.ffx.io/images/$zoom_1.0347%2C$multiply_0.7554%2C$ratio_1.777778%2C$width_1059%2C$x_0%2C$y_0/t_crop_custom/q_86%2Cf_auto/088fb7dc203448abbe934179b4f36c5831bfdd9c",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:56+00:00"
        },
        {
            "author": "Billy Heyen",
            "title": "Dodgers' Blake Snell joins perfect game Don Larsen in spotless MLB playoff history",
            "description": "It doesn't get better than this.",
            "url": "https://www.sportingnews.com/us/mlb/los-angeles-dodgers/news/dodgers-blake-snell-perfect-game-don-larsen-mlb-playoff-history/5d1a982d71e753ba08b830e1",
            "source": "Sporting News",
            "image": "https://library.sportingnews.com/styles/crop_style_16_9_desktop_webp/s3/2025-10/USATSI_27319360.jpg.webp?itok=sCaqjdzV",
            "category": "sports",
            "language": "en",
            "country": "us",
            "published_at": "2025-10-14T02:51:48+00:00"
        },
        {
            "author": "",
            "title": "Childhood friends were kidnapped together, separated and reunited",
            "description": "For part of their captivity, Guy Gilboa-Dalal and Evyatar David were together after they were kidnapped from the Nova Music Festival, they were then separated and reunited on their release.",
            "url": "https://www.smh.com.au/world/childhood-friends-were-kidnapped-together-separated-and-reunited-20251014-p5n2gb.html?ref=rss&utm_medium=rss&utm_source=rss_world",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$width_800%2C$height_450/t_crop_fill/q_86%2Cf_jpg/e5e416c972ebd364a9afa658b613547ec30438b8",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:43+00:00"
        },
        {
            "author": "",
            "title": "Childhood friends were kidnapped together, separated and reunited",
            "description": "For part of their captivity, Guy Gilboa-Dalal and Evyatar David were together after they were kidnapped from the Nova Music Festival, they were then separated and reunited on their release.",
            "url": "https://www.watoday.com.au/world/childhood-friends-were-kidnapped-together-separated-and-reunited-20251014-p5n2gb.html?ref=rss&utm_medium=rss&utm_source=rss_world",
            "source": "watoday",
            "image": "https://static.ffx.io/images/$width_800%2C$height_450/t_crop_fill/q_86%2Cf_jpg/e5e416c972ebd364a9afa658b613547ec30438b8",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:43+00:00"
        },
        {
            "author": "",
            "title": "Childhood friends were kidnapped together, separated and reunited",
            "description": "For part of their captivity, Guy Gilboa-Dalal and Evyatar David were together after they were kidnapped from the Nova Music Festival, they were then separated and reunited on their release.",
            "url": "https://www.watoday.com.au/world/childhood-friends-were-kidnapped-together-separated-and-reunited-20251014-p5n2gb.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "watoday",
            "image": "https://static.ffx.io/images/$width_800%2C$height_450/t_crop_fill/q_86%2Cf_jpg/e5e416c972ebd364a9afa658b613547ec30438b8",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:43+00:00"
        },
        {
            "author": "",
            "title": "Childhood friends were kidnapped together, separated and reunited",
            "description": "For part of their captivity, Guy Gilboa-Dalal and Evyatar David were together after they were kidnapped from the Nova Music Festival, they were then separated and reunited on their release.",
            "url": "https://www.brisbanetimes.com.au/world/childhood-friends-were-kidnapped-together-separated-and-reunited-20251014-p5n2gb.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "Brisbane Times",
            "image": "https://static.ffx.io/images/$width_800%2C$height_450/t_crop_fill/q_86%2Cf_jpg/e5e416c972ebd364a9afa658b613547ec30438b8",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:43+00:00"
        },
        {
            "author": "",
            "title": "Childhood friends were kidnapped together, separated and reunited",
            "description": "For part of their captivity, Guy Gilboa-Dalal and Evyatar David were together after they were kidnapped from the Nova Music Festival, they were then separated and reunited on their release.",
            "url": "https://www.theage.com.au/world/childhood-friends-were-kidnapped-together-separated-and-reunited-20251014-p5n2gb.html?ref=rss&utm_medium=rss&utm_source=rss_world",
            "source": "The Age",
            "image": "https://static.ffx.io/images/$width_800%2C$height_450/t_crop_fill/q_86%2Cf_jpg/e5e416c972ebd364a9afa658b613547ec30438b8",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:43+00:00"
        },
        {
            "author": "",
            "title": "Childhood friends were kidnapped together, separated and reunited",
            "description": "For part of their captivity, Guy Gilboa-Dalal and Evyatar David were together after they were kidnapped from the Nova Music Festival, they were then separated and reunited on their release.",
            "url": "https://www.smh.com.au/world/childhood-friends-were-kidnapped-together-separated-and-reunited-20251014-p5n2gb.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "The Sydney Morning Herald",
            "image": "https://static.ffx.io/images/$width_800%2C$height_450/t_crop_fill/q_86%2Cf_jpg/e5e416c972ebd364a9afa658b613547ec30438b8",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:43+00:00"
        },
        {
            "author": "",
            "title": "Childhood friends were kidnapped together, separated and reunited",
            "description": "For part of their captivity, Guy Gilboa-Dalal and Evyatar David were together after they were kidnapped from the Nova Music Festival, they were then separated and reunited on their release.",
            "url": "https://www.theage.com.au/world/childhood-friends-were-kidnapped-together-separated-and-reunited-20251014-p5n2gb.html?ref=rss&utm_medium=rss&utm_source=rss_feed",
            "source": "The Age",
            "image": "https://static.ffx.io/images/$width_800%2C$height_450/t_crop_fill/q_86%2Cf_jpg/e5e416c972ebd364a9afa658b613547ec30438b8",
            "category": "general",
            "language": "en",
            "country": "au",
            "published_at": "2025-10-14T02:51:43+00:00"
        },
        {
            "author": null,
            "title": "Duisburger Rotlichtviertel: Mann schlägt Prostituierte",
            "description": "In einem Bordell auf der Vulkanstraße in Duisburg ist es am frühen Sonntagmorgen zu einem gewalttätigen Zwischenfall gekommen.",
            "url": "https://www.radioduisburg.de/artikel/duisburger-rotlichtviertel-mann-schlaegt-prostituierte-2466068.html",
            "source": "radioduisburg",
            "image": null,
            "category": "general",
            "language": "de",
            "country": "de",
            "published_at": "2025-10-14T02:51:41+00:00"
        },
        {
            "author": "Famagusta Gazette",
            "title": "Cyprus Opens Electricity Market to Boost Competition, Cut Costs",
            "description": "The government of Cyprus has liberalized its electricity market in a bid to increase competition and reduce energy costs. Government&#8230;",
            "url": "https://famagusta-gazette.com/cyprus-opens-electricity-market-to-boost-competition-cut-costs/",
            "source": "famagusta-gazette",
            "image": null,
            "category": "general",
            "language": "en",
            "country": "us",
            "published_at": "2025-10-14T02:51:25+00:00"
        }
    ]
}